### ISSUE TITLE
New error in PhpStorm 2024.1

### ISSUE THREAD

**Issue by FeBe95** [Noorts/Toggler#64] opened 2024-04-10 14:24 UTC
The following error is popping up since I've updated to PhpStorm 2024.1. The plugin still works flawlessly though.

```Java
com.intellij.diagnostic.PluginException: `ActionUpdateThread.OLD_EDT` is deprecated and going to be removed soon. 'core.ToggleAction' must override `getActionUpdateThread` and chose EDT or BGT. See ActionUpdateThread javadoc. [Plugin: com.noorts.toggler]
	at com.intellij.diagnostic.PluginProblemReporterImpl.createPluginExceptionByClass(PluginProblemReporterImpl.java:23)
	at com.intellij.diagnostic.PluginException.createByClass(PluginException.java:90)
	at com.intellij.diagnostic.PluginException.reportDeprecatedUsage(PluginException.java:125)
	at com.intellij.openapi.actionSystem.ActionUpdateThreadAware.getActionUpdateThread(ActionUpdateThreadAware.java:21)
	at com.intellij.openapi.actionSystem.AnAction.getActionUpdateThread(AnAction.java:199)
```

System Info:
- Toggler 1.3.1
- PhpStorm 2024.1 (Build #PS-241.14494.237)
- Windows 11

**Comment by Noorts** [comment] 2024-04-11 19:50
Welcome back and thanks for the detailed report! It is much appreciated!

As the exception states it seems to be a simple deprecation.

Relevant resources:
- https://plugins.jetbrains.com/docs/intellij/basic-action-system.html#principal-implementation-overrides
- https://plugins.jetbrains.com/docs/intellij/api-notable-list-2022.html#-2a2mfp_31

I'll pick up the issue once I have a bit more time.

**Comment by Noorts** [comment] 2024-05-12 13:38
The new Toggler v1.4.0 includes platform version and Java bumps and addresses the deprecation. For the specifics check out #66.

The new update is available [here](https://github.com/Noorts/Toggler/releases/tag/v1.4.0) as a release, and will be released after approval on the marketplace in about 2 business days.

This should adequately address the deprecation warning (I wasn't able to reproduce locally). Do let me know if you run into any issues! Thanks!

**Closed as completed by Noorts** 2024-05-12 13:38 UTC
Labels: deprecation
