### ISSUE TITLE
Can't see Toggler in Android Studio settings

### ISSUE THREAD

**Issue by Cico-source** [Noorts/Toggler#5] opened 2022-03-13 22:51 UTC
Hi,

I'm using the latest version of Android Studio with Kotlin. The plugin works, but can't configure settings of it because Settings/Preferences -> Tools -> Toggler doesn't exist.

![image](https://user-images.githubusercontent.com/84936349/158082518-7a725afb-ae85-43c9-a31b-6f57a9b48a34.png)

I hope you can solve this.

**Comment by Noorts** [comment] 2022-03-14 06:45
Hey!

Thanks for letting me know 👍. I'll look into the issue soon and let you know once I know more.

**Comment by Noorts** [comment] 2022-03-14 21:08
Hey @Cico-source, I just tried to replicate the above mentioned issue, but wasn't able to.

Using the following setup the Toggler configuration page **did** show up under the Tools section.
* Freshly installed Android Studio Bumblebee
  * 2021.1.1 Patch 2
  * Build #AI-211.7628.21.2111.8193401
* Windows 10

Could you provide me with additional specifics about your setup so that I can try and reproduce the issue? Thanks!

**Comment by Cico-source** [comment] 2022-03-14 22:42
Hi,

I'm using excatly the same setup. I tried the plugin on my paralelly installed Android Studio Canary edition and there it works normally. I'll be reinstalling Android Studio in a week, so I'll let you know whether it solved the problem.

**Comment by Noorts** [comment] 2022-04-10 14:05
Hey @Cico-source! Any update yet on the issue?

**Comment by Cico-source** [comment] 2022-04-10 19:12
Hi, I'm really sorry for the delay. When I just reinstalled Android Studio, problem remained the same. But when I did a complete reinstallation where all my settings and plugins were removed, it worked.

**Comment by Noorts** [comment] 2022-04-11 17:40
@Cico-source Alright, thanks for the update 👍. I'll close the issue for now, it can be reopened if the same problem were to occur in the future.

**Comment by Cico-source** [comment] 2022-05-11 23:09
I've noticed that when I install HighlightBracketPair plugin and restart Android Studio, Toggler disappears from settings.

**Comment by Noorts** [comment] 2022-05-12 07:05
> I've noticed that when I install HighlightBracketPair plugin and restart Android Studio, Toggler disappears from settings.

Thanks for letting me know! I'll try and reproduce the issue soon.

**Comment by Noorts** [comment] 2022-05-28 13:29
Just an update:

I looked into the issue. @AprilViolet their [HighlightBracketPair](https://github.com/AprilViolet/highlight-bracket-pair) plugin once installed and once the IDE has been restarted does indeed remove Toggler's configuration page from the Tools section of the IDE's preferences.

From a brief look I wasn't able to find the cause. I'll put this on the backlog for now.

**Comment by Noorts** [comment] 2022-08-20 10:45
Hey @Cico-source! I revisited the issue today and was able to find the cause.

The identifier of Toggler's configuration menu was set to a default value which originates from the JetBrains plugin template. This identifier should be unique and because the HighlightBracketPair plugin also still uses the default value a conflict occured. I'll inform them about the issue aswell.

I've made the necessary changes to resolve the issue in 9835d4c236cf6b30e2c7b985e23b7b3476173e82 and rolled out version 1.2.8 which includes the fix. The new version is available in the [releases](https://github.com/Noorts/Toggler/releases) section and will be available on the [marketplace](https://plugins.jetbrains.com/plugin/16166-toggler) or as an update in your IDE after approval by JetBrains in about 2 business days.

The configuration menu now successfully shows up on my machine in Android Studio (I used Android Studio Bumblebee | 2021.1.1 Patch 2 on MacOS).

Once again, thanks for making me aware of the issue. If you have any feedback, then do let me know.

**Closed as completed by Noorts** 2022-08-20 10:45 UTC
Labels: bug
